### Class

Class will include short lectures, interactive activities, and time for group work. The goal of lecture is to introduce the topics and information needed for the course and get initial practice. The goal of your time outside of lecture is to further practice with topics that are introduced and deepen your understanding of material presented in class. Since so much of programming and statistical analysis is learned best by doing, we'll prioritize that throughout the course, both in and outside of the classroom.

### Course components

#### Lecture

Lectures will be your introduction to course topics and material. Lectures will be interactive, and you will be given time to practice with the lecture concepts during class. **Attendance is not required, but you should come to class**. To help incentivize this, there will be a daily participation survey that will open at the end of lecture and close shortly after each lecture. Each time you fill out the lecture survey, you get a small % of credit toward your final project Completion of all surveys will provide 1% extra credit on your final grade.

##### Readings

Readings will be suggested for some class days and are best completed prior to the day's lecture. These are meant to provide background and additional context for the upcoming day's lecture topics. These can also be a good source after class when studying or reviewing topics discussed in class.

##### Podcast

In case you miss class or would like to review the material covered in class, you can view the podcasts [here](https://podcast.ucsd.edu).

#### Labs

Labs are meant to give you deeper understanding and hands-on experience with the topics introduced during lecture in a low-stakes environment. Lab sections will typically comprise of a short review and explanation of the lab and then time for you to complete the assigned weekly lab. Labs are submitted individually, but you are encouraged to work together during lab. You are free to ask and answer each others' questions and discuss your work. Instructional staff will be present during lab to help further your understanding.

Labs are graded for concerted effort. This is because when we learn something new, mistakes are going to happen! In fact, we learn *a lot* from the mistakes we make during the learning process. If your submission reflects \~50 min of work/effort, you will receive full credit for the week's lab.

Lab attendance is not required, but is definitely encouraged if you are feeling well as you'll learn a lot by engaging with others' ideas and getting questions answered in real-time.

#### Homework

After practice in lecture and labs, homework assignments are meant to demonstrate your solidified understanding of the pre-case study course material. Homework assignments are completed and submitted individually and are marked for correctness. You *are* allowed to work together on homework assignments, but academic integrity must be upheld.

#### Projects

There will be two case study mini-projects and a final project. Teams will be randomly assigned for the first case study, but you all will select your team for the second case study and final project (which will both be completed in the same team). By working with teammates throughout the course, you will also be able to use one another as a resource during labs and assignments.

##### Case Studies

We will use case studies throughout the course to guide our learning of both programming in R and using that to analyze data. Specific case studies and statistics topics will be discussed in class. In your teams and for each of the case studies, you will: 1) carry out the analysis presented in class as a group, 2) extend the analysis from class and 3) communicate your findings for both a technical and general audience.

##### Final Project

The final project will be completed in groups, where each group will carry out a data analysis on a topic and dataset of their choosing.

Final project submissions will include a 1) detailed data science report, 2) short (5 min) in-class presentation of the project with question answering and 3) a general audience communication.

Project groups will present their projects in class during week 10.

### Grading

Your final grade will be comprised of the following:

| Assignment (#)                  | Component                   | \% of grade        |
|---------------------------------|-----------------------------|--------------------|
| **Labs (7)**                    |                             | **27% (3pt each)** |
| **Homework (2)**                |                             | **10% (5pt each)** |
| **Case Study (2; cs01 + cs02)** |                             | **28%**            |
|                                 | Report\* (2)                | 20% (10pt each)    |
|                                 | General Communication\* (2) | 6% (3pt each)      |
|                                 | Team Evaluation Survey (2)  | 2% (1pt each)      |
| **Final Project (1)**           |                             | **35%**            |
|                                 | Project Proposal\* (1)      | 3%                 |
|                                 | First Draft\* (1)           | 4%                 |
|                                 | Peer Review\* (1)           | 4%                 |
|                                 | Final Report\* (1)          | 10%                |
|                                 | General Communication\* (1) | 3%                 |
|                                 | Final Presentation (1)      | 10%                |
|                                 | Team Evaluation Survey      | 1%                 |

\* indicates group submission. Individual grades can be adjusted within a group. 


#### Final Grades

To calculate final grades, I use the standard grading scale and do not round grades up (given the numerous extra credit opportunities offered):

|         |     |
|---------|-----|
| 97-100% | A+  |
| 93-96%  | A   |
| 90-92%  | A-  |
| 87-89%  | B+  |
| 83-86%  | B   |
| 80-82%  | B-  |
| 77-79%  | C+  |
| 73-76%  | C   |
| 70-72%  | C-  |
| 67-69%  | D+  |
| 63-66%  | D   |
| 60-62%  | D-  |
| \<60%   | F   |

### Late / missed work

Late homework assignments and case study projects will be accepted up to 3 days (72 hours) after the assigned deadline. Late submissions will receive a 25% deduction.

There are no late deadlines for labs or the final project.

Note: Prof Ellis is a reasonable person; reach out to her if you have an extenuating circumstance at any point in the quarter.

### Regrade requests

We will work hard to grade everyone fairly and return assignments quickly. And, we know you also work hard and want you to receive the grade you've earned. Occasionally, grading mistakes do happen, and it's important to us to correct them. If you think there is a mistake in your grade on an assignment, post *privately* on Piazza to "Instructors" using the "regrades" tag within 72 hours. This post should include evidence of why you think your answer was correct and should point to the specific part of the assignment in question.

### Diversity & Inclusion

My goal is that every student, regardless of their background or perspective, will be well-served by this course. My philosophy is that the diversity of students in this class is a huge asset to our learning community; our differences provide opportunities for learning and understanding. I intend to present course materials that are conscious of and respectful to diversity (gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, politics, and culture); however, if I ever fall short or if you ever have suggestions for improvement, please do share with me! This feedback is always welcomed, and I am always in the process of learning and improving to this end. If you would like to provide that feedback anonymously, please use the [anonymous Google Form](https://docs.google.com/forms/d/e/1FAIpQLSd1YNH8CqBbVxr_M9v_c3X-XLqySLrBfYE7GwuAshFMCP_WvQ/viewform).\*

#### What should you call me?

Most students call me Professor/Prof Ellis, and that's great! This is how I typically sign emails to students. I'm also totally OK with you addressing me as Shannon or Dr. Ellis.

#### What I should call you?

I should call you by your preferred name, with the correct pronunciation. Please correct me (in the moment or online after the fact...however you're most comfortable) if I ever make a mistake.

### Disability Access

Students requesting accommodations due to a disability should provide a current Authorization for Accommodation (AFA) letter. These letters are issued by the Office for Students with Disabilities (OSD), which is located in University Center 202 behind Center Hall. If you are struggling to get necessary accommodations or want to further discuss your accommodations, please feel free to reach out to Professor Ellis directly.

Contacting the OSD can help you further:\
858.534.4382 (phone)\
osd\@ucsd.edu (email)\
http://disabilities.ucsd.edu

### How to get help

Class time, lab, and office hours are all great! Online communication works too, via either the class Q&A platform or email. If contacting by email, it's best to include COGS 137 in the subject line.

But, if you prefer to be anonymous (i.e. If you've been offended by an example in class, really disliked a lesson, or wish there were something covered in class that wasn't but would rather not share this publicly), please fill out the [anonymous Google Form](https://goo.gl/forms/2nXnDNbgYuS1OsGF2)\*.

\*This form can be taken down at any time if it's not being used for its intended purpose; however, you all will be notified should that happen.

### Academic integrity

Please don't cheat. Academic dishonesty undermines you actually learning the material and is unfair to students putting in the work. I take academic integrity seriously and have historically and will continue to report any suspected violations to the **UCSD Academic Integrity Office**. (I hate when I have to do this; please don't put either of us in that position.)

It is your responsibility to familiarize yourself with UCSD's academic integrity policies](http://academicintegrity.ucsd.edu/).

Examples of academic dishonesty include (but are not limited to):

- asking AI to complete your homeworks, labs, or projects
- copying answers from another student (or allowing another student to copy yours)
- using/sharing a "secret code" or timing of Google Form to receive credit when you are not in class/section (or sharing one with a classmate who is absent)

Don't cheat. Academic dishonesty undermines you actually learning the material and is unfair to students putting in the work. I take academic integrity seriously and have historically and will continue to report any suspected violations to the **UCSD Academic Integrity Office**. (I hate when I have to do this; please don't put either of us in that position.)

It is your responsibility to familiarize yourself with [UCSD's academic integrity policies](http://academicintegrity.ucsd.edu/).

Examples of academic dishonesty include (but are not limited to):

- using AI to complete your quizzes or assignments
- copying answers from another student (or allowing another student to copy yours)
- using notes or the Internet (including AI tools) during exams
- using/sharing a "secret code" or timing of Google Form to receive credit when you are not in class/section (or sharing one with a classmate who is absent)

Use of Generative AI (GenAI) tools (e.g., TritonGPT, ChatGPT, Claude, Gemini) is permitted in this course; however, use should be thoughtful and intentional. If they are helping you learn, you're probably using them correctly. If they're helping you earn points without actually learning, you're using them incorrectly.

Also, you are responsible for errors and falsehoods introduced by (any of) the tools you use. If a model hallucinates or gives you incorrect information and you submit it, you're responsible for that error.

#### Help allowed

GenAI usage is permitted on all course components; however, **it should never be asked to complete a lab, assignment, or project component for you outright. Instead you should be using it conversationally, with targeted specific tasks and/or questions.** Proper use to support learning and pitfalls to avoid will be discussed in class.

**Labs & Assignments**: Labs and assignments will be submitted individually, although you may seek help from your fellow students during completion. However, you may not give answers to each other at any time and should not ask for answers from GenAI outright. You should understand, reproduce on your own, and be able to explain any work you submit. All assignments will require you to specify how outside resources were utilized in their completion.

**Projects**: For case studies and your final project, you will work together but every person in the group is required to understand every aspect of the project. AI may be used as a collaborative tool just like an additional group member; we will discuss this in class. Use it for brainstorming, editing, debugging, formatting, background research, and/or clarifying thoughts. Individual understanding will be assessed during questions after the final presentation. Projects may include ideas and code from other sources—but these other sources must be documented with clear attribution and you may be asked to submit your case-study and/or project-related GenAI conversations.

Additional guidelines will be provided throughout the quarter.

Misuse of AI tools in this course is a form of academic dishonesty and will be handled according to UCSD's Academic Integrity policy.

#### AI Professor Use Transparency

To be clear, I think Generative AI tools are helpful! As such, I do use them in course development and like to be transparent about when I do (and do not!) use GenAI in course development. I aim to model responsible use and hope to further the conversation about how academics integrate AI into their instruction and work more broadly.

**What I use AI For**: I use AI for administrative tasks (e.g., updating the dates, links, and room numbers on the course schedule from the previous quarter, removing redundancies, clarifying policies, etc.). I also have used it to identify potential gaps lecture material, assessments, and provided resources, thus enabling me to update the course more rapidly than I was able to previously.

**What I DO NOT use AI For**: I do not use AI for designing course content from scratch, generating assessments, or evaluating your work. I consider AI a helpful assistant, akin to a knowledgeable colleague. I consider its recommendations and knowledge, but always review its output and think critically before incorporation.

**Instructor vs. Student Use**: My goal as an instructor is to effectively synthesize and communicate information to you and accurately evaluate your understanding of the material after the fact. Your job is to learn, so it is your responsibility to do the cognitive work to make that happen. Spending time and struggling through is part of that process…and honestly, sometimes even the point. Using AI to earn points without learning is an AI violation and thwarts actual learning.


### Professionalism

Please refrain from texting or using your computer for anything other than coursework during class. Not only is this distracting to you, but it can also be distracting to those around you. (Note that there is no consequence associated with this. I know it can be difficult, but I ask that you try your best!)

### 
